# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1972a27fe313a73ec463272aa205c0b60432b333af11b01c8feca371b44b374fe42d44ec9e05dde7f46dc5f0ea19bac2bb6c7790780b3a695e8dd06db90fcd88

test:
  secret_key_base: 568503d352322c9dec1d74af38faf4d7e574032113798af36e057a157140ea9f65a9d9a1158d4d6627b9fdfb694bfd842f2d7dee3e2213e73bbf312b97da7ff4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
